### ISSUE TITLE
How abou the Basic Function Form of 2-Dimensional Edge Element？

### ISSUE THREAD

**Issue by HaoWangCyy** [ocastilloreyes/petgem#1]
Hello, I'm very lucky to see your code of the 3D marine controlled-source electromagnetic (3D CSEM) method. I want to disturb you here，can you give the concrete expression of 2-dimensional basis function, such as 2-order edge element and 3-order edge element? I hope to get your reply.

**Comment by ocastilloreyes** [comment]
Hello, 

Thank you very much for your interest in **PETGEM**.

Currently, 2D high-order basis are not implemented within **PETGEM**, mainly because we are more interested in the 3D case (in addition to the lack of time).

However, in case the linear elements, also referred to as "whitney elements", are sufficient to solve your problem, we have a Matlab implementation of the linear bases of Jianming Jin's book: **Jin, JM (2015). The finite element method in electromagnetics John Wiley & Sons.** The main disadvantage of these elements could be the accuracy and convergence rate, although this will depend on your problem.

If that were not the case, you can find the complete expression for high-order 2D bases in the following  paper: [**Fuentes, F., Keith, B., Demkowicz, L., & Nagaraj, S. (2015). Orientation embedded high order shape functions for the exact sequence elements of all shapes. Computers & Mathematics with applications, 70 (4), 353-458.**](https://arxiv.org/abs/1504.03025)

I hope this is useful for you.

**Comment by HaoWangCyy** [comment]
Thank you very much for your reply and help！

**Comment by ocastilloreyes** [comment]
You are welcome!
